basePath: '{{.BasePath}}'
definitions:
  api.Response:
    properties:
      error:
        type: string
    type: object
  api.TransactionRequest:
    properties:
      tx:
        items:
          type: integer
        type: array
    type: object
  api.TransactionsRequest:
    properties:
      txs:
        items:
          type: '&{%!s(token.Pos=410) <nil> byte}'
        type: array
    type: object
host: '{{.Host}}'
info:
  contact: {}
  description: Iniate a websocket connection
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: blockmania API
  version: "1.0"
paths:
  /api/pubsub/ws:
    get:
      description: Iniate a websocket connection
      operationId: websocket
      responses:
        "204": {}
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Response'
            type: object
      summary: Initiate a websocket connection in order to subscribed to object saved
        in chainspace by the current node
      tags:
      - pubsub
  /api/transaction:
    post:
      consumes:
      - application/json
      description: Add a new transction in the blockchain
      operationId: addTransction
      parameters:
      - description: transaction
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/api.TransactionRequest'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Response'
            type: object
      summary: Add a new transaction in the blockchain
      tags:
      - blockmania
  /api/transactions:
    post:
      consumes:
      - application/json
      description: Add a list of new transctions in the blockchain
      operationId: addTransactions
      parameters:
      - description: transactions
        in: body
        name: transactions
        required: true
        schema:
          $ref: '#/definitions/api.TransactionsRequest'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Response'
            type: object
      summary: Add a list of new transactions in the blockchain
      tags:
      - blockmania
swagger: "2.0"
